### ISSUE TITLE
Update reusable dockerfile workflow to use matrices

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/.github#7]
## Overview
Allow for matrices

## Design or Proposal
GitHub reusable workflows don't support `strategy` so this post details a work around

https://github.community/t/reusable-workflow-with-strategy-matrix/205676

Caller workflow
```
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: waldos-woof/actions-automation/.github/workflows/main.yml@main
    with: 
      versions: "[\"14.x\", \"16.x\"]"
```
reusable workflow
```
name: Node.js CI

on:
  workflow_call:
    inputs:
      versions:
        description: 'Stringified JSON object listing target Node versions'
        default: '14.x'
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ${{fromJson(inputs.versions)}}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  ```
